// <auto-generated />
namespace GymManagementSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class AddLink_KhuyenMai_GoiTap : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddLink_KhuyenMai_GoiTap));
        
        string IMigrationMetadata.Id
        {
            get { return "202508101442224_AddLink_KhuyenMai_GoiTap"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
